### ISSUE TITLE
[feature request] allow FeatureTable[Frequency] as input

### ISSUE THREAD

**Issue by cdiener** [cduvallet/q2-perc-norm#3]
Hi,

It would be great if the plugin could directly work on `FeatureTable[Frequency]` data without having to convert to `FeatureTable[RelativeFrequency]` first.

This might make it easier to connect the output of the denoising steps to percentile normalization.

**Comment by cduvallet** [comment]
@cdiener - I've been thinking about this and I think it's actually better if I don't include this in the code. My thinking: if you're doing anything on `FeatureTable[RelativeFrequency]`, you want that conversion to be clearly tracked in the provenance. 

But if I include `FeatureTable[Frequency]` as an allowed input, that conversion won't be explicitly tracked in your code (and you might have users who don't really understand the method or what it's doing). By forcing users to convert to `FeatureTable[RelativeFrequency]`, we make sure that they are fully aware of every step they're taking. (Which is something that is very important to me).

When I talked about this with the QIIME 2 developers, they mentioned that we could write a QIIME 2 pipeline that first does the relative frequency conversion and then percentile normalizes. This would also track the conversion in the provenance, and is probably fairly simple to write. I don't feel strongly enough about this to put in the work to code that up, but you are certainly welcome to! Or you can ask another Gibbons lab member interested in software dev to do it -- I'd be happy to chat with them and help them figure out the process! :)

**Comment by cdiener** [comment]
That makes sense. I think the larger priority is probably to make it possible to pass percentile normalized data to other plugins such as `diversity` and this seems to be tracked by #2.

**Comment by cduvallet** [comment]
Yeah, it is sort of tracked by that except that back when I went and tried to add `PercentileNormalized` data to qiime2 plugins, the core devs had to do some work to allow for multiple input/output types. And now I've lost most of my motivation to make these edits, *SO* if you see any function where `PercentileNormalized` support would be useful please flag it for me and I can go in and make those changes! Just don't have time to go prowling through qiime2 core plugins to find everywhere that it belongs...

Also, fwiw, if there's someone in the Gibbons lab who wants to get involved with QIIME 2 development I would be more than happy to train them up and hand this off to them :D

**Comment by cdiener** [comment]
Cool, I'll cycle that around and see if someone wants to take that on.
