### ISSUE TITLE
Case/Control column should validate for present values

### ISSUE THREAD

**Issue by ElDeveloper** [cduvallet/q2-perc-norm#5]
If the case/control column (`--m-metadata-column`) includes values that are not 'Case' or 'Control', the plugin should throw an error. Otherwise if no Case or Control values are present, this leads to a misleading exception along the lines of `"There aren't enough controls in your data....."`.

**Comment by cduvallet** [comment]
Good point! Will try to make those edits soon.

**Comment by cduvallet** [comment]
Commit d2c29056a218a52611a0e65f0c5e305ea15af56d addresses this. Version 2019.4.1 has this update is on conda! Thanks @ElDeveloper

**Comment by ElDeveloper** [comment]
Thanks so much, that's great to hear!
