### ISSUE TITLE
plugin error 

### ISSUE THREAD

**Issue by Abbie-Williams** [cduvallet/q2-perc-norm#6]
Tried normalizing data in qiime2-2021.2 and received plug-in error that dataframe object has no attribute 'to_dense'. Then tried this with the test data supplied on GitHub and the example code in the tutorial and received the same error. 

Full error: 

Plugin error from perc-norm:

  'DataFrame' object has no attribute 'to_dense'

Debug info has been saved to /var/folders/pq/k8m6x2152g31jm4_h1jgfzh0ty92hv/T/qiime2-q2cli-err-2a7x1f81.log

**Comment by jeffchen2000** [comment]
1) open the log file (in your case: qiime2-q2cli-err-2a7x1f81.log)
2) find a file something like "_percentile_normalize.py" and open with a text editor
3) in the file, find "df = table.to_dataframe().to_dense().T"
4) change it to  "df = table.to_dataframe().sparse.to_dense().T" and save
4) and just re-run your command, should be fixed

**Comment by cduvallet** [comment]
I am no longer actively maintaining this plugin (or working in the microbiome space generally), but feel free to make that change & test it and open a PR, happy to merge it. If how to move forward isn't immediately obvious to you or this message is intimidating, happy to hop on a quick call and walk you through how to do it. (The folks on the developer section of the qiime2 forum would also be more than thrilled to help you as well!)

**Comment by nmacknight** [comment]
I had the same issue and using jeffchen2000's [comment](https://github.com/cduvallet/q2-perc-norm/issues/6#issuecomment-1247475123). I managed to successfully create the intended percentile normalized .qza file.

I'd like to add my notes to help others. 

When Receiving this error:

Full error:
Plugin error from perc-norm:
'DataFrame' object has no attribute 'to_dense'

open your log where this was saved. Im on a mac so I "nano" the path
Example: nano /var/folders/zd/_4cb91ls16x2y1xp0s4lhq5jxn8jjd/T/qiime2-q2cli-err-128d99a6.log

You will see where your computer is reading the "df = table.to_dataframe().to_dense().T" by looking at the line above that "df = table.to_dataframe().to_dense().T". 

Go to that location on your computer, open "_percentile_normalize.py" to change "df = table.to_dataframe().to_dense().T" to "df = table.to_dataframe().sparse.to_dense().T" as instructed by jeffchen2000. 

Once saved you should re-run your code and have a successful outcome by resolving this error.

**Comment by cduvallet** [comment]
Thanks @jeffchen2000 and @nmacknight ! Like I said above, I'm no longer using qiime but am happy to make these changes to the codebase so that future users don't encounter this issue.

If you're new to open-source, I'm happy to set up a zoom call and walk you through how to make the change and make a PR to incorporate it. (If you know what those words mean, feel free to open a PR and I can merge it)

**Comment by cduvallet** [comment]
Addressed by #7 , will be updating the conda distribution soon
