### ISSUE TITLE
Steps for downstream analyses in qiime2

### ISSUE THREAD

**Issue by Alenap26** [cduvallet/q2-perc-norm#8]
Hello, thank you for providing this package. 
I'm trying to integrate it into a pipeline that utilizes qiime2. I'm encountering difficulties in integrating the output type (FeatureTable[PercentileNormalized]) generated by q2-perc-norm. 
I need to incorporate this output into the subsequent pipeline command as input.table:

`qiime diversity core-metrics-phylogenetic --i-phylogeny {input.tree} --i-table {input.table} etc..`

Could you suggest the steps to use the output of q2-perc-norm in downstream analyses?

**Comment by cduvallet** [comment]
Hi @Alenap26 - please see this forum post with an answer to your question: https://forum.qiime2.org/t/q2-perc-norm-questions/9171

If you have additional questions on how to use the plugin, please use the qiime 2 forum. (This repo is for reporting issues/bugs with the code)
